name: Tests Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: anb-rising-stars

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        env:
          TESTING: 'true'
        run: python -m pytest tests/ -v --tb=short

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-results
          path: anb-rising-stars/tests/
          retention-days: 7

  api-tests:
    name: API Tests with Newman
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: anb-rising-stars
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: anb_user
          POSTGRES_PASSWORD: anb_password
          POSTGRES_DB: anb_rising_stars
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI
        run: |
          python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Wait for FastAPI
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8000/ | grep -q "ANB Rising Stars"; then
              echo "FastAPI is ready"
              break
            fi
            sleep 2
          done

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Newman
        run: npm install

      - name: Run API tests
        run: |
          mkdir -p reports
          npx newman run collections/postman_environment.json \
            --reporters cli,json \
            --reporter-json-export reports/api-tests.json \
            --timeout 10000

      - name: Upload API test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-tests-results
          path: anb-rising-stars/reports/
          retention-days: 7
